# Generated by Django 5.1.5 on 2025-01-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ramen_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ramenshop",
            old_name="opening_hours",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="ramenshop",
            old_name="scraped_date",
            new_name="features",
        ),
        migrations.RemoveField(
            model_name="ramenshop",
            name="address",
        ),
        migrations.RemoveField(
            model_name="ramenshop",
            name="location_latitude",
        ),
        migrations.RemoveField(
            model_name="ramenshop",
            name="location_longitude",
        ),
        migrations.AddField(
            model_name="ramenshop",
            name="dinner_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ramenshop",
            name="distance_from_station",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ramenshop",
            name="lunch_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ramenshop",
            name="payment_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ramenshop",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ramenshop",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
