# Generated by Django 5.1.5 on 2025-01-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ramen_app", "0002_rename_opening_hours_ramenshop_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ramenshop",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ramenshop",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ramenshop",
            name="url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
