# Generated by Django 5.1.5 on 2025-01-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ramen_app", "0003_ramenshop_address_alter_ramenshop_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ramenshop",
            name="address",
        ),
        migrations.AddField(
            model_name="ramenshop",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ramenshop",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
